"""initial schema

Revision ID: 84754ebe15e8
Revises: 
Create Date: 2026-08-02 20:21:12.941872
"""
from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '84754ebe15e8'
down_revision: Optional[str] = None
branch_labels: Optional[Union[str, Sequence[str]]] = None
depends_on: Optional[Union[str, Sequence[str]]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apitoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('revoked_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apitoken_expires_at'), 'apitoken', ['expires_at'], unique=False)
    op.create_index(op.f('ix_apitoken_token_hash'), 'apitoken', ['token_hash'], unique=True)
    op.create_index(op.f('ix_apitoken_user_id'), 'apitoken', ['user_id'], unique=False)
    op.create_table('cartitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartitem_guest_token'), 'cartitem', ['guest_token'], unique=False)
    op.create_index(op.f('ix_cartitem_product_id'), 'cartitem', ['product_id'], unique=False)
    op.create_index(op.f('ix_cartitem_user_id'), 'cartitem', ['user_id'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_slug'), 'category', ['slug'], unique=True)
    op.create_table('deliveryshipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pickup_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pickup_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pickup_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pickup_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dropoff_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('items_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_total', sa.Float(), nullable=False),
    sa.Column('cod_amount', sa.Float(), nullable=False),
    sa.Column('provider_payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_event_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveryshipment_external_ref'), 'deliveryshipment', ['external_ref'], unique=False)
    op.create_index(op.f('ix_deliveryshipment_order_id'), 'deliveryshipment', ['order_id'], unique=True)
    op.create_index(op.f('ix_deliveryshipment_provider'), 'deliveryshipment', ['provider'], unique=False)
    op.create_index(op.f('ix_deliveryshipment_provider_job_id'), 'deliveryshipment', ['provider_job_id'], unique=False)
    op.create_index(op.f('ix_deliveryshipment_store_id'), 'deliveryshipment', ['store_id'], unique=False)
    op.create_table('devicetoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expo_push_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devicetoken_device_id'), 'devicetoken', ['device_id'], unique=False)
    op.create_index(op.f('ix_devicetoken_expo_push_token'), 'devicetoken', ['expo_push_token'], unique=True)
    op.create_index(op.f('ix_devicetoken_user_id'), 'devicetoken', ['user_id'], unique=False)
    op.create_table('inventorybalance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventorybalance_product_id'), 'inventorybalance', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventorybalance_warehouse_id'), 'inventorybalance', ['warehouse_id'], unique=False)
    op.create_table('moderationevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('to_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('flags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderationevent_product_id'), 'moderationevent', ['product_id'], unique=False)
    op.create_table('moderationjob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('flags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('finished_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderationjob_product_id'), 'moderationjob', ['product_id'], unique=False)
    op.create_index(op.f('ix_moderationjob_status'), 'moderationjob', ['status'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delivery_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('inventory_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confirmation_expires_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confirmed_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cancelled_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cancellation_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('payment_group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('qpay_invoice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('qpay_payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ebarimt_receiver_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ebarimt_receiver', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ebarimt_district_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ebarimt_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ebarimt_lottery', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ebarimt_qr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ebarimt_payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_confirmation_expires_at'), 'order', ['confirmation_expires_at'], unique=False)
    op.create_index(op.f('ix_order_inventory_status'), 'order', ['inventory_status'], unique=False)
    op.create_index(op.f('ix_order_payment_group_id'), 'order', ['payment_group_id'], unique=False)
    op.create_index(op.f('ix_order_qpay_invoice_id'), 'order', ['qpay_invoice_id'], unique=False)
    op.create_index(op.f('ix_order_qpay_payment_id'), 'order', ['qpay_payment_id'], unique=False)
    op.create_index(op.f('ix_order_store_id'), 'order', ['store_id'], unique=False)
    op.create_index(op.f('ix_order_user_id'), 'order', ['user_id'], unique=False)
    op.create_table('orderitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderitem_order_id'), 'orderitem', ['order_id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pack_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('images', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('video', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('ratio', sa.Integer(), nullable=True),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.Column('tread_percent', sa.Integer(), nullable=True),
    sa.Column('bolt_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wheel_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('car_make', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('listing_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('barcode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('publish_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('moderation_flags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submitted_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_barcode'), 'product', ['barcode'], unique=False)
    op.create_index(op.f('ix_product_car_make'), 'product', ['car_make'], unique=False)
    op.create_index(op.f('ix_product_category_id'), 'product', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_listing_kind'), 'product', ['listing_kind'], unique=False)
    op.create_index(op.f('ix_product_publish_status'), 'product', ['publish_status'], unique=False)
    op.create_index(op.f('ix_product_sku'), 'product', ['sku'], unique=False)
    op.create_index(op.f('ix_product_store_id'), 'product', ['store_id'], unique=False)
    op.create_table('stockmovement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stockmovement_movement_type'), 'stockmovement', ['movement_type'], unique=False)
    op.create_index(op.f('ix_stockmovement_product_id'), 'stockmovement', ['product_id'], unique=False)
    op.create_index(op.f('ix_stockmovement_store_id'), 'stockmovement', ['store_id'], unique=False)
    op.create_index(op.f('ix_stockmovement_warehouse_id'), 'stockmovement', ['warehouse_id'], unique=False)
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_owner_id'), 'store', ['owner_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_store_id'), 'warehouse', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouse_store_id'), table_name='warehouse')
    op.drop_table('warehouse')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_store_owner_id'), table_name='store')
    op.drop_table('store')
    op.drop_index(op.f('ix_stockmovement_warehouse_id'), table_name='stockmovement')
    op.drop_index(op.f('ix_stockmovement_store_id'), table_name='stockmovement')
    op.drop_index(op.f('ix_stockmovement_product_id'), table_name='stockmovement')
    op.drop_index(op.f('ix_stockmovement_movement_type'), table_name='stockmovement')
    op.drop_table('stockmovement')
    op.drop_index(op.f('ix_product_store_id'), table_name='product')
    op.drop_index(op.f('ix_product_sku'), table_name='product')
    op.drop_index(op.f('ix_product_publish_status'), table_name='product')
    op.drop_index(op.f('ix_product_listing_kind'), table_name='product')
    op.drop_index(op.f('ix_product_category_id'), table_name='product')
    op.drop_index(op.f('ix_product_car_make'), table_name='product')
    op.drop_index(op.f('ix_product_barcode'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_orderitem_order_id'), table_name='orderitem')
    op.drop_table('orderitem')
    op.drop_index(op.f('ix_order_user_id'), table_name='order')
    op.drop_index(op.f('ix_order_store_id'), table_name='order')
    op.drop_index(op.f('ix_order_qpay_payment_id'), table_name='order')
    op.drop_index(op.f('ix_order_qpay_invoice_id'), table_name='order')
    op.drop_index(op.f('ix_order_payment_group_id'), table_name='order')
    op.drop_index(op.f('ix_order_inventory_status'), table_name='order')
    op.drop_index(op.f('ix_order_confirmation_expires_at'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_moderationjob_status'), table_name='moderationjob')
    op.drop_index(op.f('ix_moderationjob_product_id'), table_name='moderationjob')
    op.drop_table('moderationjob')
    op.drop_index(op.f('ix_moderationevent_product_id'), table_name='moderationevent')
    op.drop_table('moderationevent')
    op.drop_index(op.f('ix_inventorybalance_warehouse_id'), table_name='inventorybalance')
    op.drop_index(op.f('ix_inventorybalance_product_id'), table_name='inventorybalance')
    op.drop_table('inventorybalance')
    op.drop_index(op.f('ix_devicetoken_user_id'), table_name='devicetoken')
    op.drop_index(op.f('ix_devicetoken_expo_push_token'), table_name='devicetoken')
    op.drop_index(op.f('ix_devicetoken_device_id'), table_name='devicetoken')
    op.drop_table('devicetoken')
    op.drop_index(op.f('ix_deliveryshipment_store_id'), table_name='deliveryshipment')
    op.drop_index(op.f('ix_deliveryshipment_provider_job_id'), table_name='deliveryshipment')
    op.drop_index(op.f('ix_deliveryshipment_provider'), table_name='deliveryshipment')
    op.drop_index(op.f('ix_deliveryshipment_order_id'), table_name='deliveryshipment')
    op.drop_index(op.f('ix_deliveryshipment_external_ref'), table_name='deliveryshipment')
    op.drop_table('deliveryshipment')
    op.drop_index(op.f('ix_category_slug'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_cartitem_user_id'), table_name='cartitem')
    op.drop_index(op.f('ix_cartitem_product_id'), table_name='cartitem')
    op.drop_index(op.f('ix_cartitem_guest_token'), table_name='cartitem')
    op.drop_table('cartitem')
    op.drop_index(op.f('ix_apitoken_user_id'), table_name='apitoken')
    op.drop_index(op.f('ix_apitoken_token_hash'), table_name='apitoken')
    op.drop_index(op.f('ix_apitoken_expires_at'), table_name='apitoken')
    op.drop_table('apitoken')
    # ### end Alembic commands ###
